### ISSUE TITLE
Webapp Not reachable

### ISSUE THREAD

**Issue by JennySachweh** [wjiang/ctf-simulation#5]
In case you're not aware yet: https://ctfsimulation.streamlit.app/ seems to be currently malfuctioning. When opening the link, I only get shown "Error running app. If this keeps happening, please contact support.", instead of the WebApp. This has been going on for the last few hours. As I really like the many options in this CTF simulator, I'd love if you could bring it back to life. Thanks for your great work!

**Comment by wjiang** [comment]
Thanks for reporting the issue. It is up running again.

**Comment by JennySachweh** [comment]
Thanks! I was able to open it, but unfortunately it crashed after a few minutes again. Not sure whether anything about what I'm doing is causing this behavior.
